import { defineLesson } from '../definitions';

export const lesson = defineLesson({
  schemaVersion: 3,
  id: 'conditions-and-branches',
  slug: 'conditions-and-branches',
  version: '3.0.0',
  courseId: 'python-foundations',
  title: 'Conditions and Branches',
  subtitle: 'Ask a question and choose one path.',
  goal: 'Understand Boolean guards, selected paths, and if/else outcomes.',
  lens: { initialProgramId: 'age-sixteen', initialView: 'flow' },
  sections: [
    { id: 'decision-idea', heading: 'A program can decide', internalRole: 'introduce', lensCueId: 'conditions-introduce', blocks: [{ type: 'prose', paragraphs: ['A condition asks a true-or-false question.', 'Python executes only the branch selected by that answer.'] }, { type: 'definition', text: 'A branch is one possible path through a decision.' }] },
    { id: 'condition-shape', heading: 'Read the decision shape', internalRole: 'structural-model', lensCueId: 'conditions-shape', blocks: [{ type: 'code-shape', title: 'Guard and two paths', rows: [{ label: 'Guard', code: 'if age >= 18:', explanation: 'Asks a Boolean question.', tone: 'input' }, { label: 'True path', code: 'status = "adult"', explanation: 'Runs when the guard is true.', tone: 'work' }, { label: 'False path', code: 'else: status = "minor"', explanation: 'Runs when the guard is false.', tone: 'output' }] }] },
    { id: 'predict-branch', heading: 'Predict the branch', internalRole: 'predict', lensCueId: 'conditions-predict', blocks: [{ type: 'value-prediction', responseId: 'conditions-branch-prediction', prompt: 'For age 16, predict 0 for the false path or 1 for the true path.', fields: [{ id: 'branch', label: 'branch', expected: 0 }] }] },
    { id: 'follow-branch', heading: 'Follow the selected path', internalRole: 'guided-explore', lensCueId: 'conditions-guided', blocks: [{ type: 'observation', text: 'Watch the guard evaluate and confirm that only the selected branch changes State.' }] },
    { id: 'change-condition', heading: 'Change the condition input', internalRole: 'variation', lensCueId: 'conditions-explore', blocks: [{ type: 'variation-prediction', responseId: 'conditions-age-prediction', prompt: 'Which result changes when age becomes 21?', options: ['status'], expected: ['status'], variationId: 'age-twenty-one' }] },
    { id: 'recognize-decision', heading: 'Recognize another decision', internalRole: 'recognize', lensCueId: 'conditions-recognize', blocks: [{ type: 'recognition-check', responseId: 'conditions-recognition', prompt: 'Classify the decision parts.', source: 'if score >= 50:\n    result = "pass"\nelse:\n    result = "retry"', roles: [{ id: 'guard', label: 'Boolean guard' }, { id: 'outcome', label: 'branch outcome' }], items: [{ id: 'score >= 50', label: 'score >= 50', expectedRole: 'guard' }, { id: 'result', label: 'result assignments', expectedRole: 'outcome' }], successFeedback: 'Correct: the comparison is the guard and the assignments produce branch outcomes.', retryFeedback: 'Find the true-or-false expression after if, then find what each branch assigns.' }] },
    { id: 'build-decision', heading: 'Build a decision', internalRole: 'produce', lensCueId: 'conditions-build', blocks: [{ type: 'build', responseId: 'conditions-build-response', prompt: 'Build a supported if/else decision that assigns status on both paths.', programId: 'conditions-build-scaffold', verificationIds: ['conditions-build-supported', 'conditions-build-shape', 'conditions-build-coverage'], criteria: ['Use a Boolean if/else guard.', 'Assign status on both paths.', 'Keep both deterministic scenarios supported.'] }] },
  ],
  programs: [
    { id: 'age-sixteen', source: 'age = 16\nif age >= 18:\n    status = "adult"\nelse:\n    status = "minor"', argsText: '' },
    { id: 'age-twenty-one', source: 'age = 21\nif age >= 18:\n    status = "adult"\nelse:\n    status = "minor"', argsText: '' },
    { id: 'recognize-pass', source: 'score = 65\nif score >= 50:\n    result = "pass"\nelse:\n    result = "retry"', argsText: '' },
    { id: 'conditions-build-scaffold', source: 'age = 16\nif age >= 18:\n    status = ""\nelse:\n    status = ""', argsText: '' },
  ],
  scenarios: [
    { id: 'age-16', label: 'Age 16', programId: 'age-sixteen', verificationIds: [] },
    { id: 'age-21', label: 'Age 21', programId: 'age-twenty-one', verificationIds: ['conditions-adult-value'] },
  ],
  variations: [{
    id: 'age-twenty-one',
    label: 'Age 21',
    applyLabel: 'Run age 21',
    programId: 'age-twenty-one',
    predictionId: 'conditions-age-prediction',
    verificationIds: ['conditions-adult-value', 'conditions-build-coverage'],
    comparison: { kind: 'path', baselineProgramId: 'age-sixteen', fields: [] },
    successFeedback: 'The alternate input selects the other branch.',
    retryFeedback: 'Compare the guard outcomes and resulting path.',
  }],
  cues: [
    { id: 'conditions-introduce', sectionId: 'decision-idea', apply: 'initialize-once', presentation: 'quiet', mode: 'observe', programId: 'age-sixteen', view: 'flow', frame: 'start', editing: 'locked', eyebrow: 'Learning Lens · waiting', title: 'One question, one selected path', instruction: 'Start with the decision idea.' },
    { id: 'conditions-shape', sectionId: 'condition-shape', apply: 'guide-without-reset', presentation: 'visible', mode: 'observe', view: 'structure', frame: 'start', editing: 'locked', eyebrow: 'Observe', title: 'See the guard and branches', instruction: 'Match syntax to the decision structure.' },
    { id: 'conditions-predict', sectionId: 'predict-branch', apply: 'guide-without-reset', presentation: 'quiet', mode: 'observe', view: 'state', frame: 'start', editing: 'locked', revealPolicy: { responseId: 'conditions-branch-prediction', unlockAt: 'committed', concealedViews: ['state', 'explain', 'structure'], preCommitFrame: 'start' }, eyebrow: 'Predict first', title: 'The selected path is concealed', instruction: 'Commit the branch prediction before execution.' },
    { id: 'conditions-guided', sectionId: 'follow-branch', apply: 'guide-without-reset', presentation: 'focus', mode: 'guided', view: 'explain', frame: 'start', editing: 'locked', requiresResponseId: 'conditions-branch-prediction', eyebrow: 'Guided', title: 'Follow the selected path', instruction: 'Step through the guard and selected assignment.' },
    { id: 'conditions-explore', sectionId: 'change-condition', apply: 'guide-without-reset', presentation: 'visible', mode: 'explore', view: 'state', frame: 'end', editing: 'authored-variations', eyebrow: 'Explore', title: 'Try the other scenario', instruction: 'Predict, then run the alternate age.' },
    { id: 'conditions-recognize', sectionId: 'recognize-decision', apply: 'replace-program', presentation: 'visible', mode: 'observe', programId: 'recognize-pass', view: 'structure', frame: 'start', editing: 'locked', revealPolicy: { responseId: 'conditions-recognition', unlockAt: 'revealed', concealedViews: ['state', 'explain', 'structure'], preCommitFrame: 'start' }, eyebrow: 'Recognize', title: 'Same decision structure', instruction: 'Classify the decision parts before viewing Lens.' },
    { id: 'conditions-build', sectionId: 'build-decision', apply: 'replace-program', presentation: 'focus', mode: 'build', programId: 'conditions-build-scaffold', view: 'state', frame: 'start', editing: 'free', eyebrow: 'Build', title: 'Build a two-path decision', instruction: 'Use the shared editor and semantic checks.' },
  ],
  verifications: [
    { id: 'conditions-adult-value', type: 'binding-values', expectedBindings: { status: "'adult'" } },
    { id: 'conditions-build-supported', type: 'supported-execution' },
    { id: 'conditions-build-shape', type: 'branch-shape', requireElse: true, resultBinding: 'status' },
    { id: 'conditions-build-coverage', type: 'branch-coverage', expectedOutcomes: [false, true] },
  ],
});
