import { defineLesson } from '../definitions';

export const lesson = defineLesson({
  schemaVersion: 3,
  id: 'values-and-variables',
  slug: 'values-and-variables',
  version: '3.0.0',
  courseId: 'python-foundations',
  title: 'Values and Variables',
  subtitle: 'Give values names, then build new values from them.',
  goal: 'Understand how assignment binds a name to a value and how later expressions reuse it.',
  lens: { initialProgramId: 'price-tax-total', initialView: 'flow' },
  sections: [
    {
      id: 'names-for-values',
      heading: 'A name for a value',
      internalRole: 'introduce',
      lensCueId: 'cue-introduce',
      blocks: [
        { type: 'prose', paragraphs: ['Programs remember information by giving values useful names.', 'A good name lets later statements reuse a value without repeating it.'] },
        { type: 'definition', text: 'A variable is a name that currently refers to a value.' },
        { type: 'callout', label: 'Notice', text: 'The equals sign assigns a value. It does not ask whether two things are equal.', tone: 'notice' },
      ],
    },
    {
      id: 'assignment-shape',
      heading: 'Read an assignment',
      internalRole: 'structural-model',
      lensCueId: 'cue-assignment',
      blocks: [{
        type: 'assignment-shape',
        title: 'Three complete assignments, one dependency chain',
        lines: [
          { source: 'price = 100', target: 'price', operator: '=', expression: '100', dependencies: [] },
          { source: 'tax = price * 0.16', target: 'tax', operator: '=', expression: 'price * 0.16', dependencies: ['price'] },
          { source: 'total = price + tax', target: 'total', operator: '=', expression: 'price + tax', dependencies: ['price', 'tax'] },
        ],
      }],
    },
    {
      id: 'predict-values',
      heading: 'What will Python store?',
      internalRole: 'predict',
      lensCueId: 'cue-predict',
      blocks: [{
        type: 'value-prediction',
        responseId: 'prediction-values',
        prompt: 'Before running the program, predict the values Python will store.',
        fields: [
          { id: 'tax', label: 'tax', expected: 16 },
          { id: 'total', label: 'total', expected: 116 },
        ],
      }],
    },
    {
      id: 'follow-calculation',
      heading: 'Follow the calculation',
      internalRole: 'guided-explore',
      lensCueId: 'cue-guided',
      blocks: [{ type: 'observation', text: 'Step through each binding and compare the final values with your committed prediction.' }],
    },
    {
      id: 'change-value',
      heading: 'Change one value',
      internalRole: 'variation',
      lensCueId: 'cue-explore',
      blocks: [{
        type: 'variation-prediction',
        responseId: 'prediction-change',
        prompt: 'If the starting value changes to 200, which stored values will change?',
        options: ['price', 'tax', 'total'],
        expected: ['price', 'tax', 'total'],
        variationId: 'price-200',
      }],
    },
    {
      id: 'recognize-structure',
      heading: 'Recognize the same structure',
      internalRole: 'recognize',
      lensCueId: 'cue-recognize',
      blocks: [{
        type: 'recognition-check',
        responseId: 'recognition-bindings',
        prompt: 'Classify each name by its role.',
        source: 'distance = 120\ntime = 2\nspeed = distance / time',
        roles: [
          { id: 'starting', label: 'starting name' },
          { id: 'derived', label: 'derived name' },
        ],
        items: [
          { id: 'distance', label: 'distance', expectedRole: 'starting' },
          { id: 'time', label: 'time', expectedRole: 'starting' },
          { id: 'speed', label: 'speed', expectedRole: 'derived' },
        ],
        successFeedback: 'Correct: the first two names hold starting values and the third is derived from them.',
        retryFeedback: 'Check which lines use literal values and which line reads earlier names.',
      }],
    },
    {
      id: 'build-calculation',
      heading: 'Build a calculation',
      internalRole: 'produce',
      lensCueId: 'cue-build',
      blocks: [{
        type: 'build',
        responseId: 'build-calculation',
        prompt: 'Create two starting values and one value calculated from both.',
        programId: 'build-scaffold',
        verificationIds: ['build-supported', 'build-assignment-count', 'build-dependencies'],
        criteria: ['Use three assignments.', 'Make the final assignment depend on both starting names.', 'Use supported Python that runs successfully.'],
      }],
    },
  ],
  programs: [
    { id: 'price-tax-total', source: 'price = 100\ntax = price * 0.16\ntotal = price + tax', argsText: '' },
    { id: 'price-tax-total-200', source: 'price = 200\ntax = price * 0.16\ntotal = price + tax', argsText: '' },
    { id: 'distance-time-speed', source: 'distance = 120\ntime = 2\nspeed = distance / time', argsText: '' },
    { id: 'build-scaffold', source: 'first = 10\nsecond = 5\nresult = 0', argsText: '' },
  ],
  scenarios: [],
  variations: [{
    id: 'price-200',
    label: 'Starting value 200',
    applyLabel: 'Apply the 200 variation',
    programId: 'price-tax-total-200',
    predictionId: 'prediction-change',
    verificationIds: ['variation-values'],
    comparison: {
      kind: 'bindings',
      baselineProgramId: 'price-tax-total',
      fields: [
        { key: 'price', label: 'price' },
        { key: 'tax', label: 'tax' },
        { key: 'total', label: 'total' },
      ],
    },
    successFeedback: 'All configured bindings changed as predicted.',
    retryFeedback: 'Compare each configured baseline and changed value.',
  }],
  cues: [
    { id: 'cue-introduce', sectionId: 'names-for-values', apply: 'initialize-once', presentation: 'quiet', mode: 'observe', programId: 'price-tax-total', view: 'flow', frame: 'start', editing: 'locked', eyebrow: 'Learning Lens · waiting', title: 'The same workspace follows the whole lesson', instruction: 'Start with the idea. Lens is ready when execution becomes useful.' },
    { id: 'cue-assignment', sectionId: 'assignment-shape', apply: 'guide-without-reset', presentation: 'visible', mode: 'observe', view: 'structure', frame: 'start', editing: 'locked', eyebrow: 'Observe', title: 'See the assignment structure', instruction: 'Match each source line to its target, expression, and dependencies.' },
    { id: 'cue-predict', sectionId: 'predict-values', apply: 'guide-without-reset', presentation: 'quiet', mode: 'observe', view: 'state', frame: 'start', editing: 'locked', revealPolicy: { responseId: 'prediction-values', unlockAt: 'committed', concealedViews: ['state', 'explain', 'structure'], preCommitFrame: 'start' }, eyebrow: 'Predict first', title: 'Execution is concealed', instruction: 'Commit both predictions before Lens reveals stored values.' },
    { id: 'cue-guided', sectionId: 'follow-calculation', apply: 'guide-without-reset', presentation: 'focus', mode: 'guided', view: 'explain', frame: 'start', editing: 'locked', requiresResponseId: 'prediction-values', eyebrow: 'Guided', title: 'Follow the dependency chain', instruction: 'Use the frame controls to follow each binding.' },
    { id: 'cue-explore', sectionId: 'change-value', apply: 'guide-without-reset', presentation: 'visible', mode: 'explore', view: 'state', frame: 'end', editing: 'authored-variations', eyebrow: 'Explore', title: 'Apply an authored variation', instruction: 'Commit which bindings change, then apply the variation.' },
    { id: 'cue-recognize', sectionId: 'recognize-structure', apply: 'replace-program', presentation: 'visible', mode: 'observe', programId: 'distance-time-speed', view: 'structure', frame: 'start', editing: 'locked', revealPolicy: { responseId: 'recognition-bindings', unlockAt: 'revealed', concealedViews: ['state', 'explain', 'structure'], preCommitFrame: 'start' }, eyebrow: 'Recognize', title: 'Same structure, different names', instruction: 'Classify the roles before inspecting Lens.' },
    { id: 'cue-build', sectionId: 'build-calculation', apply: 'replace-program', presentation: 'focus', mode: 'build', programId: 'build-scaffold', view: 'state', frame: 'start', editing: 'free', eyebrow: 'Build', title: 'Use the real Lens editor', instruction: 'Edit, run, and check the declared semantic requirements.' },
  ],
  verifications: [
    { id: 'variation-values', type: 'binding-values', expectedBindings: { price: '200', tax: '32.0', total: '232.0' } },
    { id: 'build-supported', type: 'supported-execution' },
    { id: 'build-assignment-count', type: 'assignment-count', expected: 3 },
    { id: 'build-dependencies', type: 'assignment-dependencies', requiredDependencies: { result: ['first', 'second'] } },
  ],
});
